#!/bin/bash

export DOCKER_CONTENT_TRUST=0
export XAUTH=/tmp/.docker.xauth
export XSOCK=/tmp/.X11-unix

RUNTIME=${RUNTIME:-runc}
WALLET=${WALLET:-qux}

docker run -d --name ${WALLET}-wallet --runtime ${RUNTIME} --volume=$XSOCK:$XSOCK:rw --volume=$XAUTH:$XAUTH:rw --env XAUTHORITY=$XAUTH --env DISPLAY=$DISPLAY --volume=${WALLET}:/data --env ELECTRUM_MODE=GUI electrum-daemon
